services:

  # Python App
  python_app:
    image: python_app:${PYTHON_APP_VERSION}
    restart: always
    container_name: wheather_quality
    networks:
      - python_app
    ports:
      - "4003:${PYTHON_APP_PORT}"

networks:
  python_app:
    driver: bridge
